//
// Created by c16fld on 2018-09-24.
//

#ifndef CHAT_SERVICE_PDU_HANDLER_CLIENT_NAMESERVER_H
#define CHAT_SERVICE_PDU_HANDLER_CLIENT_NAMESERVER_H


#define OP_GETLIST 3
#define OP_SLIST 4

#endif //CHAT_SERVICE_PDU_HANDLER_CLIENT_NAMESERVER_H
