//
// Created by dv16jjo on 2018-09-26.
//

#ifndef CHAT_SERVICE_TEST_PDU_HANDLER_SERVER_NAMESERVER_H
#define CHAT_SERVICE_TEST_PDU_HANDLER_SERVER_NAMESERVER_H

void test_creating_reg();

#endif //CHAT_SERVICE_TEST_PDU_HANDLER_SERVER_NAMESERVER_H
